name: Build tailscale for loong64

permissions: write-all

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'tailscale upstream version'
        required: true
        default: 'v1.96.4'
jobs:
  debian:
    name: Build tailscale for loong64
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      
      - name: Checkout tailscale sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: tailscale/tailscale
          ref: ${{ github.event.inputs.version }}
          submodules: recursive

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up loong64 Debian container
        uses: maus007/docker-run-action-fork@5ddaad0f7eedd03f64e412b1931852bd3031b273
        with:
          image: ghcr.io/loong64/loongnix:25
          options: --cpus=4 --platform linux/loong64 --privileged -v ${{ github.workspace }}:/work
          run: |
            cd /work
            apt update; apt install sudo git build-essential devscripts equivs -y
            git config --global --add safe.directory /work
            mk-build-deps -i -r -t "apt -y --no-install-recommends"
            dpkg-buildpackage -b -uc -us
            mkdir -p output_artifacts
            mv ../*.deb output_artifacts/
            
            
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tailscale for loong64
          path: ${{ github.workspace }}/output_artifacts/*
          compression-level: 0
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
